"""Add skip condition fields to commands and server_results

Revision ID: 0980a1d0a699
Revises: 95ceab51bb25
Create Date: 2025-09-03 11:01:15.247608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0980a1d0a699'
down_revision = '95ceab51bb25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skip_condition_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('skip_condition_type', sa.String(length=20), nullable=True))

    with op.batch_alter_table('execution_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skipped_commands', sa.Integer(), nullable=False, server_default='0'))

    with op.batch_alter_table('server_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skipped', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.add_column(sa.Column('skip_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('skip_condition_result', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('server_results', schema=None) as batch_op:
        batch_op.drop_column('skip_condition_result')
        batch_op.drop_column('skip_reason')
        batch_op.drop_column('skipped')

    with op.batch_alter_table('execution_history', schema=None) as batch_op:
        batch_op.drop_column('skipped_commands')

    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.drop_column('skip_condition_type')
        batch_op.drop_column('skip_condition_id')

    # ### end Alembic commands ###
