"""Add 6-column format fields to commands table

Revision ID: 12aa62b15a68
Revises: 7702e3c74477
Create Date: 2025-08-29 10:19:18.434572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12aa62b15a68'
down_revision = '7702e3c74477'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extract_method', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('comparator_method', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('command_id_ref', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.drop_column('command_id_ref')
        batch_op.drop_column('comparator_method')
        batch_op.drop_column('extract_method')
    # ### end Alembic commands ###
