"""Add JobTracking model

Revision ID: 1eb49c4a1ef5
Revises: a1b2c3d4e5f6
Create Date: 2025-09-19 08:47:47.462859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eb49c4a1ef5'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=255), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('current_command', sa.Integer(), nullable=True),
    sa.Column('total_commands', sa.Integer(), nullable=True),
    sa.Column('current_server', sa.Integer(), nullable=True),
    sa.Column('total_servers', sa.Integer(), nullable=True),
    sa.Column('job_type', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('mop_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('result_summary', sa.JSON(), nullable=True),
    sa.Column('server_info', sa.JSON(), nullable=True),
    sa.Column('redis_status_key', sa.String(length=255), nullable=True),
    sa.Column('redis_progress_key', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_tracking', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_tracking_job_id'), ['job_id'], unique=True)

    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.alter_column('ssh_port',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('22'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.alter_column('ssh_port',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('22'))

    with op.batch_alter_table('job_tracking', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_tracking_job_id'))

    op.drop_table('job_tracking')
    # ### end Alembic commands ###
