"""Update commands table structure

Revision ID: 406f0fe8e749
Revises: 4f57ab7f58b3
Create Date: 2025-08-12 19:19:07.532894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '406f0fe8e749'
down_revision = '4f57ab7f58b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('command_text', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('order_index', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('is_critical', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('timeout_seconds', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('expected_output', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('rollback_command', sa.Text(), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('command',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('reference_value',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('execution_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('command_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('executed_by', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('server_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('duration', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('dry_run', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('exit_code', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('output', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('error_output', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('target_servers', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('execution_mode', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('total_commands', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('completed_commands', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('executed_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'users', ['executed_by'], ['id'])
        batch_op.create_foreign_key(None, 'commands', ['command_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('execution_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('executed_at')
        batch_op.drop_column('completed_commands')
        batch_op.drop_column('total_commands')
        batch_op.drop_column('execution_mode')
        batch_op.drop_column('target_servers')
        batch_op.drop_column('error_output')
        batch_op.drop_column('output')
        batch_op.drop_column('exit_code')
        batch_op.drop_column('dry_run')
        batch_op.drop_column('duration')
        batch_op.drop_column('completed_at')
        batch_op.drop_column('started_at')
        batch_op.drop_column('status')
        batch_op.drop_column('server_id')
        batch_op.drop_column('executed_by')
        batch_op.drop_column('command_id')

    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.alter_column('reference_value',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('command',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.drop_column('rollback_command')
        batch_op.drop_column('expected_output')
        batch_op.drop_column('timeout_seconds')
        batch_op.drop_column('is_critical')
        batch_op.drop_column('order_index')
        batch_op.drop_column('description')
        batch_op.drop_column('command_text')

    # ### end Alembic commands ###
