"""Add condition_value field to commands table

Revision ID: 49c9f68181fb
Revises: 0980a1d0a699
Create Date: 2025-09-04 08:58:30.545147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49c9f68181fb'
down_revision = '0980a1d0a699'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skip_condition_value', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.drop_column('skip_condition_value')
    # ### end Alembic commands ###
