"""Add user status and viewer role support

Revision ID: 6b895c71d938
Revises: c3c6205dbe55
Create Date: 2025-08-19 09:27:55.606482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b895c71d938'
down_revision = 'c3c6205dbe55'
branch_labels = None
depends_on = None


def upgrade():
    # B1: Thêm cột cho phép NULL để tránh lỗi
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('pending_expires_at', sa.DateTime(), nullable=True))

    # B2: Gán giá trị mặc định cho các user cũ
    op.execute("UPDATE users SET status = 'active' WHERE status IS NULL")

    # B3: Đặt lại constraint NOT NULL
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('status', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('pending_expires_at')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
