"""add risk_reports table

Revision ID: 7c3882cb5571
Revises: f1b3f319b87c
Create Date: 2025-08-08 11:20:42.096957

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7c3882cb5571'
down_revision = 'f1b3f319b87c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('execution_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('excel_path', sa.Text(), nullable=False),
    sa.Column('log_path', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['execution_history.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_reports')
    # ### end Alembic commands ###
