"""Add servers table for server management

Revision ID: 95ce388141f0
Revises: 49c9f68181fb
Create Date: 2025-09-09 08:29:52.894429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95ce388141f0'
down_revision = '49c9f68181fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('ssh_port', sa.String(length=10), nullable=True),
    sa.Column('admin_username', sa.String(length=100), nullable=False),
    sa.Column('admin_password', sa.Text(), nullable=False),
    sa.Column('root_username', sa.String(length=100), nullable=False),
    sa.Column('root_password', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('servers')
    # ### end Alembic commands ###
