"""Add periodic_assessments table

Revision ID: 95ceab51bb25
Revises: 12aa62b15a68
Create Date: 2025-08-29 16:01:38.033282

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '95ceab51bb25'
down_revision = '12aa62b15a68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('periodic_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mop_id', sa.Integer(), nullable=False),
    sa.Column('assessment_type', sa.String(length=20), nullable=False),
    sa.Column('frequency', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', name='periodicfrequency'), nullable=False),
    sa.Column('execution_time', sa.String(length=5), nullable=False),
    sa.Column('server_info', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'INACTIVE', 'COMPLETED', name='periodicstatus'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_execution', sa.DateTime(), nullable=True),
    sa.Column('next_execution', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['mop_id'], ['mops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('periodic_assessment_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('periodic_assessment_id', sa.Integer(), nullable=False),
    sa.Column('assessment_result_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('execution_logs', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_result_id'], ['assessment_results.id'], ),
    sa.ForeignKeyConstraint(['periodic_assessment_id'], ['periodic_assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('periodic_assessment_executions')
    op.drop_table('periodic_assessments')
    # ### end Alembic commands ###
