"""Allow nullable fields for MOP upload

Revision ID: 9b32661f7b8d
Revises: c801dd514171
Create Date: 2025-08-14 10:59:11.742086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b32661f7b8d'
down_revision = 'c801dd514171'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mops', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('priority',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('estimated_duration',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('risk_level',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mops', schema=None) as batch_op:
        batch_op.alter_column('risk_level',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('estimated_duration',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('priority',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
