"""empty message

Revision ID: 9cb178704783
Revises: 
Create Date: 2025-08-08 00:55:45.429236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cb178704783'
down_revision = '5e0606c06fea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('mops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.ARRAY(sa.String(length=20)), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mop_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('command', sa.Text(), nullable=False),
    sa.Column('reference_value', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['mop_id'], ['mops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('execution_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mop_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('execution_time', sa.DateTime(), nullable=True),
    sa.Column('risk_assessment', sa.Boolean(), nullable=True),
    sa.Column('handover_assessment', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['mop_id'], ['mops.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mop_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mop_id', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(length=10), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mop_id'], ['mops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mop_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mop_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['mop_id'], ['mops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('server_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('execution_id', sa.Integer(), nullable=False),
    sa.Column('server_ip', sa.String(length=45), nullable=False),
    sa.Column('command_id', sa.Integer(), nullable=False),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['command_id'], ['commands.id'], ),
    sa.ForeignKeyConstraint(['execution_id'], ['execution_history.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('server_results')
    op.drop_table('mop_reviews')
    op.drop_table('mop_files')
    op.drop_table('execution_history')
    op.drop_table('commands')
    op.drop_table('mops')
    op.drop_table('users')
    # ### end Alembic commands ###
