"""Add assessment_type to MOP model

Revision ID: c3c6205dbe55
Revises: 9b32661f7b8d
Create Date: 2025-08-14 15:50:14.980727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3c6205dbe55'
down_revision = '9b32661f7b8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mops', schema=None) as batch_op:
        # Add column as nullable first
        batch_op.add_column(sa.Column('assessment_type', sa.String(length=50), nullable=True))
    
    # Update existing records with default value
    op.execute("UPDATE mops SET assessment_type = 'handover_assessment' WHERE assessment_type IS NULL")
    
    # Make column non-nullable
    with op.batch_alter_table('mops', schema=None) as batch_op:
        batch_op.alter_column('assessment_type', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mops', schema=None) as batch_op:
        batch_op.drop_column('assessment_type')

    # ### end Alembic commands ###
