"""Add execution_logs and error_message to AssessmentResult

Revision ID: c801dd514171
Revises: 0a182138f0fa
Create Date: 2025-08-14 01:11:46.812836

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c801dd514171'
down_revision = '0a182138f0fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('execution_logs', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('error_message', sa.Text(), nullable=True))

    with op.batch_alter_table('mops', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('pending', 'approved', name='mopstatus'),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mops', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('pending', 'approved', name='mopstatus'),
               existing_nullable=False)

    with op.batch_alter_table('assessment_results', schema=None) as batch_op:
        batch_op.drop_column('error_message')
        batch_op.drop_column('execution_logs')

    # ### end Alembic commands ###
