"""add stderr and return_code to server_results

Revision ID: f1b3f319b87c
Revises: 9cb178704783
Create Date: 2025-08-08 09:08:20.927056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1b3f319b87c'
down_revision = '9cb178704783'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('server_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stderr', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('return_code', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('server_results', schema=None) as batch_op:
        batch_op.drop_column('return_code')
        batch_op.drop_column('stderr')

    # ### end Alembic commands ###
